### ISSUE TITLE
Do something while file is downloading... 

### ISSUE THREAD

**Issue by naatogmagithub** [Smile-SA/cordova-plugin-fileopener#8]
Is there a way of calling a function or showing a loading spinner when the app is downloading the file from a server?
Which method should I invoke?

**Comment by marob** [comment]
Nothing is designed for this in the plugin, but you could try:

```javascript
var onSuccess = function(data) {
    hideSpinner();
    // Do something
};
function onError(error) {
    hideSpinner();
    // Do something
}
showSpinner();
window.cordova.plugins.FileOpener.openFile("http://www.website.com/file.pdf", onSuccess, onError);
```

with `showSpinner` and `hideSpinner`, 2 functions that manages the spinner display.

**Comment by naatogmagithub** [comment]
Thanks , I will try it.

**Comment by naatogmagithub** [comment]
That works perfect. I love this plugin

**Comment by marob** [comment]
Thanks!
